<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */



$this->title = 'Privacy Policy';
$baseurl = Yii::$app->request->baseurl;
//$this->params['breadcrumbs'][] = $this->title;
?>
<?php 
$this->registerJsFile($baseurl . "/js/scroll.js", ['position' => yii\web\View::POS_END, 'depends' => ['yii\web\JqueryAsset']]);
?>

<?php $this->registerCssFile($baseurl . "/css/above.css", ['position' => yii\web\View::POS_READY, 'depends' => ['yii\bootstrap\BootstrapAsset']]); ?>

<div class="site-login">
    <div class="row">
        <div class="col-lg-12">
            <div class="inner-content"> 
                <div class="main-title heading">InJoy Global Privacy Policy</div>
                <div class="main-title">Effective Date: August 17, 2016</div>
                <div class="description">The InJoy Global Privacy Policy (this "Policy") applies to all personal information we handle (except as noted below) including online, offline, and manually-processed data. The practices outlined in this Policy apply to websites, blogs, mobile sites, and applications maintained by or on behalf of InJoy Global, Inc. ("InJoy Global"), including <u>www.injoyglobal.com and InJoy Global, Inc.'s Culti-vate platform (collectively, the "Website")</u>. It does not apply to other companies' or organizations' web sites to which we link. You should carefully review the privacy policies of those web sites in order to determine how your personal information is treated by such third parties.</div>
                <div class="heading"><u>GENERAL POLICIES</u></div>
                <div class="description">By using this website, you agree to the terms of this Policy and expressly consent to the processing of information and session data according to the terms contained herein. InJoy Global reserves the right, in its sole discretion, to make changes to this Policy.</div>
                <div class="heading">Consent</div>       
                <div class="description">InJoy Global expects its customers have received all required consents according to applicable privacy laws from their employees before transferring in printed, electronic, facsimile or any other format-personally identifiable information to InJoy Global.<br><br>All information website visitors submit is voluntary. Submitting information constitutes your consent for InJoy Global to use the information for the purpose stated and indicates to us that you are aware of this Policy's provisions. <br><br> We reserve the right to change or modify this Policy at any time. Any changes to the Policy will be posted to this website. Please check the effective date at the top of this page to determine if this Policy has been modified since you last reviewed it. Your use of the website after the modification implies that you consent to the changes. </div>
                <div class="heading">Cookies</div>
                <div class="description">Cookies are files that web servers place on an Internet user's browser that are designed to store basic information, such as visitor preferences. The use of cookies on the website allows visitors to enjoy more seamless visits and more accurately measures visitor behavior on the website.<br>The cookies used on the website do not identify you personally. They merely recognize your browser, unless you choose to identify yourself voluntarily. You may choose to identify yourself for the following reason: so the browser will remember your username and password.<br><br>We may use session and persistent cookies. Session cookies exist only during an Internet user's online session. They disappear (or expire) from the user's computer when he/she closes the browser software.<br><br>Persistent cookies remain on the user's browser after the browser has been closed. We may place persistent cookies on your web browser to remember your information and settings when you visit our website at a future date. This makes your experience more convenient, meaningful, and relevant. When you come to the website, our web server uses persistent cookies to improve your interaction with the website by, for example, remembering your preferences and dynamically serving more relevant content to you. We use cookies to identify the fact that you are one of our customers or a prior website visitor (as applicable). Visitors who disable their web browsers' ability to accept cookies will still be able to browse the website, however, they may lose some of the functionality provided by the use of cookies.<br><br>We may also use first-party and third-party cookies. First-party cookies are served directly by the website to your computer's browser and are only used by the website operator, who recognizes your computer when you revisit our website. Third-party cookies are served to your computer through one of our service providers on behalf of a website operator.<br><br>You have the ability to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. For further information about disabling cookies you can visit <a href="http://www.allaboutcookies.org" target="_blank">www.allaboutcookies.org</a>. If you choose to decline cookies, you may not be able to login or use other interactive features of our websites and services that depend on cookies.</div>
                <div class="heading">Customer Information Collection &amp; Use</div>
                <div class="description">In the administration of our culture shaping and employee wellness business, we collect certain employee data so that we may effectively administer the culture-shaping rewards and recognition programs and determine an employee's eligibility for awards in accordance with the criteria established by the employer. We will ask for no more information than is needed to fulfill our contractual obligation with the employer.<br>The second context pertains to surveys. The surveys we conduct are in connection with the administration of our employee culture shaping and recognition business and are for the benefit of the employer. We collect data in the aggregate based on the information entered by the employee. This information, except where prohibited by law, may be included in reports distributed to management from time to time. We may also conduct marketing surveys for data research purposes only. The information provided is used for research analysis and we analyze the answers in the aggregate. A person's cooperation is absolutely voluntary; he or she may withdraw from a marketing research study at any time. No personal details will be sought without the employer's prior consent. We may ask for contact details in the event we need to verify or validate answers. We may also ask for demographic information.<br><br>Information provided in response to or in connection with a survey, whether collected through a website or through traditional market research tools, and whether provided at the request of an employer or for market research, is and may be provided to our client(s) and/or other entities and/or the public as part of cumulative market research information or statistical data in the ordinary course, but without identifying the participants individually directly or indirectly. We may also collect and/or ask for statements in the form of testimonials which may be used again on the site or in promotional collateral from time to time.<br><br>Your information may be disclosed by you or at your direction, on blogs, forums, social media and other services to which you are able to post information and materials.  You should be aware that any information you disclose through these services will become public information, and may be available to the general public.  You authorize us to share your information with your social media account provider if you connect your use of our services to any of your social media accounts.<br><br>The basic, personally identifiable information that InJoy Global collects in order to perform and improve its services includes: names, birthdates, hire dates, employee number other employment information, usernames, mailing address, email address, phone number, height, weight and other information requested of participants of a contest.</div><br><br> 
                <div class="heading"><u>OTHER PRIVACY MATTERS</u></div>
                <div class="heading">California Do Not Track Notice Disclosures:</div>
                <div class="description">We do not track the personally identifiable information of our users and visitors over time and across third party websites to provide targeted advertising.  Consequently, we do not respond to Do Not Track (DNT) signals.  Other third party websites may keep track of your browsing activities and personally identifiable information over time and across different websites when they provide you with content, which enables them to customize what they present to you on their websites. These third party websites may continue to track you while you use this website.</div>
                <div class="heading">Children's Online Privacy Protection Act Compliance</div> 
                <div class="description">We do not intentionally collect personally identifiable information about children under the age of 13 and assume all user accounts are opened by adults. If you are under the age of 18 (but at least 13 years of age) you may use this website only under the supervision of a parent or legal guardian who agrees to be bound by Terms of Use posted on this website ("Terms of Use"). Children under the age of 13 may not use this website, and parents or legal guardians may not agree to the Terms of Use on their behalf. If you do not agree to (or cannot comply with) any of the Terms of Use, do not use this website.
                </div> 
                <div class="heading">California Residents</div>
                <div class="description">California Civil Code Section 1798.83 permits visitors to web sites who are residents of California to request information regarding the web site owner's disclosure of their personal information to third parties for direct marketing purposes.It is our policy not to disclose your personal information to third parties for direct marketing purposes. </div>
                <div class="heading">International Data Transfer </div> 
                <div class="description">We may transfer information that we collect about you, including personal information, to affiliated entities, or to other third parties (as provided herein) across borders and from your country or jurisdiction to other countries or jurisdictions around the world. If you are located in the European Union or other regions with laws governing data collection and use that may differ from U.S. law, please note that you are transferring information, including personal information, to a country and jurisdiction that does not have the same data protection laws as your jurisdiction, and you consent to the transfer of information to the U.S. and the use and disclosure of information about you, including personal information, as described in this Privacy Policy.</div> 
                <div class="heading">Transfer of Data Abroad</div> 
                <div class="description">If you are visiting this Site from a country other than the country in which our servers are located, your communications with us may result in the transfer of information&nbsp;across international boundaries. By visiting this Site and communicating electronically with us, you consent to such transfers.</div>
                <div class="heading"><u>Security</u></div>
                <div class="description">The security of your personal information is important to us. Although we take reasonable steps to safeguard and to prevent unauthorized access to your private information, we cannot be responsible for the acts of those who gain unauthorized access and we make no warranty we will prevent unauthorized access to your private information.<br><br>IN NO EVENT SHALL INJOY GLOBAL, OR ITS AFFILIATES, BE LIABLE FOR ANY DAMAGES (WHETHER CONSEQUENTIAL, DIRECT, INDIRECT, PUNITIVE, SPECIAL OR OTHERWISE) ARISING OUT OF, OR IN ANY WAY CONNECTED WITH, A THIRD PARTY'S UNAUTHORISED ACCESS TO YOUR DETAILS, REGARDLESS OF WHETHER SUCH DAMAGES ARE BASED ON CONTRACT, STRICT LIABILITY, TORT OR OTHER THEORIES OF LIABILITY, AND ALSO REGARDLESS OF WHETHER WE WERE GIVEN ACTUAL OR CONSTRUCTIVE NOTICE THAT DAMAGES WERE POSSIBLE.</div>
                <div class="note heading"><u>Notice and Choice</u></div> 
                <div class="heading">Disclosures and Transfers</div>
                <div class="description">InJoy Global will not disclose an individual's personal data to third parties, except when one or more of the following conditions is true:
                    <ul>                         
                        <li>We have the individual's permission to make the disclosure;</li>
                        <li>The disclosure is required by law;</li>
                        <li>The disclosure will aid in the protection of InJoy's rights and property;</li>
                        <li>There is an emergency, such as when we believe someone's safety is at risk;</li>
                        <li>The disclosure of the information will protect against misuse of our websites and services;</li>
                        <li>The disclosure is reasonably related to the sale or disposition of all or part of InJoy Global's business;</li>
                        <li>The information in question is publicly available; or</li>
                        <li>The disclosure is reasonably necessary for the establishment or defense of legal claims.</li>
                    </ul>
                </div>
                <div class="heading">Access and Correction</div>
                <div class="description">If an individual becomes aware that information InJoy Global maintains about that individual is inaccurate, or if an individual wishes to update or review his or her information, the individual may contact InJoy Global at info@injoyglobal.com. InJoy Global will take reasonable steps to permit individuals to correct, amend, or delete information that is demonstrated to be inaccurate. The individual will need to provide sufficient identifying information, such as name, address, hiring date and employee number. We may request additional identifying information as a security precaution. In addition, we may limit or deny access to personal details where providing such access would be unreasonably burdensome or expensive in the circumstances. In some circumstances, InJoy Global may charge a reasonable fee, where warranted, for access to personal information. </div>
                <div class="heading">Enforcement and Dispute Resolution</div>
                <div class="description">InJoy Global utilizes the self-assessment approach to assure its compliance with its privacy statement. InJoy Global periodically verifies that this Policy is accurate, comprehensive for the information intended to be covered, prominently displayed, completely implemented, and in conformity with the Safe Harbor Principles. InJoy Global encourages interested persons to raise any concerns with it, using the contact details below. InJoy Global will investigate and attempt to resolve complaints and disputes regarding use and disclosure of personal information in accordance with the principles contained in this Policy.
                </div>
                <div class="heading"><u>Data</u></div>
                <div class="heading">Data Security</div>
                <div class="description">To prevent unauthorized access or disclosure, maintain data accuracy, and ensure the appropriate use and confidentiality of information, either for its own purposes or on behalf of its clients, InJoy Global has put in place appropriate physical, electronic and managerial procedures to safeguard and secure the information we process. However, InJoy Global cannot guarantee the security of information on or transmitted via the Internet.
                </div> 
                <div class="heading">Data Integrity</div> 
                <div class="description">InJoy Global processes personal information only in ways compatible with the purpose for which it was collected or authorized by the individual. To the extent necessary for such purposes, we take reasonable steps to make sure that personal details are accurate, complete, current and otherwise reliable with regard to their intended use.
                </div> 
                <div class="heading"><u>Contact Information</u></div> 
                <div class="description">Written questions or comments regarding this Policy and our certifications should be submitted to InJoy Global by mail as follows:</div>
                <div class="address">
                    InJoy Global, Inc.<br>
                    General Counsel<br>
                    5348 Vegas Dr.<br>
                    Las Vegas, NV 89108 USA
                </div>
            </div>
        </div> 
    </div>   
    <a href="javascript:" id="return-to-top"><i class="fa fa-arrow-up"></i></a>
</div>